theme: jekyll-theme-cayman
title: Portfolio de Virgile73
description: Portfolio de Virgile Millé du 28/08/2025, fait pour montrer les réalisations faites durant mon BUT informatique.
author: Virgile Millé
email: virgile2607@gmail.com
github_username: Virgile73
linkedin: www.linkedin.com/in/virgile-millé-7b71a12b3
